### ISSUE TITLE
Upgrade nicht Möglich?!? "Fatal Python error"

### ISSUE THREAD

**Issue by Ewies** [alexreinert/piVCCU#210]
Hallo,

ich versuche piVCCU zu upgraden aber bekomme immer diese Fehlermeldung:

`
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
ValueError: bad marshal data (invalid reference)
Aborted
E: Unterprozess /usr/bin/apt-listchanges --apt || test $? -lt 10 hat Fehlercode zurückgegeben (1)
E: Failure running script /usr/bin/apt-listchanges --apt || test $? -lt 10
`

was könnte ich dagegen tun???

Mfg Steffen

**Comment by alexreinert** [comment]
Das ist kein piVCCU Problem, sondern ein Raspbian Problem. Das hier dürfte aber helfen: https://superuser.com/questions/1469664/apt-broken-on-raspbian-stretch-dpkg-exiting

**Comment by alexreinert** [comment]
Ist hier noch etwas offen?

**Comment by alexreinert** [comment]
Scheinbar nicht --> Closed
